# Change these first
owner: safe-global # Your GitHub organization or username, where this repository lives
repo: safe-services-status # The name of this repository
skipTopicsUpdate: true
sites:
  - name: Safe Client Gateway
    url: https://safe-client.safe.global/health/ready/
  - name: Safe Tx Service (Mainnet)
    url: https://safe-transaction-mainnet.safe.global/check/
  - name: Safe Tx Service (Gnosis Chain)
    url: https://safe-transaction-gnosis-chain.safe.global/check/
  - name: Safe Tx Service (Sepolia)
    url: https://safe-transaction-sepolia.safe.global/check/
  - name: Safe Tx Service (Binance Smart Chain)
    url: https://safe-transaction-bsc.safe.global/check/
  - name: Safe Tx Service (Polygon - Matic)
    url: https://safe-transaction-polygon.safe.global/check/
  - name: Safe Tx Service (Polygon - zkEVM)
    url: https://safe-transaction-zkevm.safe.global/check/
  - name: Safe Tx Service (Base Mainnet)
    url: https://safe-transaction-base.safe.global/check/
  - name: Safe Tx Service (Base Sepolia)
    url: https://safe-transaction-base-sepolia.safe.global/check/
  - name: Safe Tx Service (Celo)
    url: https://safe-transaction-celo.safe.global/check/
  - name: Safe Tx Service (Arbitrum)
    url: https://safe-transaction-arbitrum.safe.global/check/
  - name: Safe Tx Service (Avalanche)
    url: https://safe-transaction-avalanche.safe.global/check/
  - name: Safe Tx Service (Optimism)
    url: https://safe-transaction-optimism.safe.global/check/
  - name: Safe Tx Service (Aurora)
    url: https://safe-transaction-aurora.safe.global/check/
  - name: Safe Tx Service (zkSync Era Mainnet)
    url: https://safe-transaction-zksync.safe.global/check/
  - name: Safe Tx Service (xLayer)
    url: https://safe-transaction-xlayer.safe.global/check/
  - name: Safe Tx Service (Scroll)
    url: https://safe-transaction-scroll.safe.global/check/
  - name: Safe Tx Service (Linea)
    url: https://safe-transaction-linea.safe.global/check/
  - name: Safe Tx Service (Chiado)
    url: https://safe-transaction-chiado.safe.global/check/
  - name: Safe Tx Service (Mantle)
    url: https://safe-transaction-mantle.safe.global/check/
  - name: Safe Tx Service (Sonic)
    url: https://safe-transaction-sonic.safe.global/check/
  - name: Safe Tx Service (Ink)
    url: https://safe-transaction-ink.safe.global/check/
  - name: Safe Tx Service (Unichain)
    url: https://safe-transaction-unichain.safe.global/check/
  - name: Safe Tx Service (Berachain)
    url: https://safe-transaction-berachain.safe.global/check/
  - name: Safe Tx Service (Lens)
    url: https://safe-transaction-lens.safe.global/check/
  - name: Safe Tx Service (Hemi)
    url: https://safe-transaction-hemi.safe.global/check/
  - name: Safe Tx Service (Katana)
    url: https://safe-transaction-katana.safe.global/check/
  - name: Safe Tx Service (Peaq)
    url: https://safe-transaction-peaq.safe.global/check/
  - name: Safe Tx Service (Codex)
    url: https://safe-transaction-codex.safe.global/check/
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.safe.global
  # baseUrl: /safe-services-status
  logoUrl: https://pbs.twimg.com/profile_images/1643941027898613760/gyhYEOCE_400x400.jpg
  name: Safe Services Status
  introTitle: Status for the **Safe Services**
  introMessage: Safe Services Status
  favicon: https://app.safe.global/favicon.ico
  navbar:
    - title: Indexing Status
      href: https://status.safe.global
    - title: Safe Infrastructure
      href: https://github.com/safe-global/safe-infrastructure
    - title: Help docs
      href: https://help.safe.global/en/
    - title: Dev docs
      href: https://docs.safe.global/
